/* plugin zquery */
INSERT INTO `queries` VALUES (1, NULL, 'Mes tâches (assignées ou créées)', '---\nstatus_id:\n  :operator: \"!\"\n  :values:\n  - \'3\'\n  - \'5\'\n  - \'6\'\nand_any:\n  :operator: \"=\"\n  :values:\n  - Inclus\nauthor_id:\n  :operator: \"=\"\n  :values:\n  - me\nassigned_to_id:\n  :operator: \"=\"\n  :values:\n  - me\n',1,NULL,'---\n- - done_ratio\n  - desc\n- - priority\n  - desc\n- - id\n  - desc\n','','IssueQuery',2,'---\n:totalable_names:\n- :estimated_hours\n:draw_relations: \n:draw_progress_line: \n');

/* plugin Issue Checklist */
INSERT INTO `settings` (`name`, `value`, `updated_on`) VALUES ('plugin_redmine_issue_checklist', '--- !ruby/hash:ActionController::Parameters\nsave_log: \'1\'\n', NOW()) ON DUPLICATE KEY UPDATE `value` = '--- !ruby/hash:ActionController::Parameters\nsave_log: \'1\'\n', `updated_on` = NOW();

/* plugin Scheduling Poll */
INSERT INTO `settings` (`name`, `value`, `updated_on`) VALUES ('plugin_redmine_scheduling_poll', '--- !ruby/hash:ActionController::Parameters\nscheduling_vote_value_5: \'\'\nscheduling_vote_value_4: \'\'\nscheduling_vote_value_3: Présent (sûr!)\nscheduling_vote_value_2: Présent (à confirmer)\nscheduling_vote_value_1: Absent\nscheduling_poll_item_date_format: dd/mm/yy\n', NOW()) ON DUPLICATE KEY UPDATE `value` = '--- !ruby/hash:ActionController::Parameters\nscheduling_vote_value_5: \'\'\nscheduling_vote_value_4: \'\'\nscheduling_vote_value_3: Présent (sûr!)\nscheduling_vote_value_2: Présent (à confirmer)\nscheduling_vote_value_1: Absent\nscheduling_poll_item_date_format: dd/mm/yy\n', `updated_on` = NOW();

/* plugin Tab */
INSERT INTO `custom_fields` VALUES (NULL,'ProjectCustomField','Onglet Collaboratif','text',NULL,'',NULL,NULL,0,0,0,1,0,'',1,0,0,'--- !ruby/hash:ActiveSupport::HashWithIndifferentAccess\ntext_formatting: \'\'\n','Ce champ supplémentaire permet de stocker le contenu HTML de l\'onglet Collaboratif de chaque projet');
INSERT INTO `settings` (`name`, `value`, `updated_on`) VALUES ('plugin_redmine_tab', '--- !ruby/hash:ActionController::Parameters\ntab_name: Collaboratif\ntab_text: \'1\'\nsystem_tab_name: \'\'\nsystem_tab_text: \'\'\n', NOW()) ON DUPLICATE KEY UPDATE `value` = '--- !ruby/hash:ActionController::Parameters\ntab_name: Collaboratif\ntab_text: \'1\'\nsystem_tab_name: \'\'\nsystem_tab_text: \'\'\n', `updated_on` = NOW();

/* plugin Recurring Tasks */
INSERT INTO `settings` (`name`, `value`, `updated_on`) VALUES ('plugin_recurring_tasks', '--- !ruby/hash:ActionController::Parameters\njournal_attributed_to_user: \'1\'\nshow_top_menu: \'0\'\nreopen_issue: \'1\'\n', NOW()) ON DUPLICATE KEY UPDATE`value` = '--- !ruby/hash:ActionController::Parameters\njournal_attributed_to_user: \'1\'\nshow_top_menu: \'0\'\nreopen_issue: \'1\'\n', `updated_on` = NOW();

/* plugin DMSF */
INSERT INTO `settings` (`name`, `value`, `updated_on`) VALUES ('plugin_redmine_dmsf', '--- !ruby/hash:ActionController::Parameters\ndmsf_max_file_upload: \'10\'\ndmsf_max_file_download: \'10\'\ndmsf_max_email_filesize: \'35\'\ndmsf_max_ajax_upload_filesize: \'10\'\ndmsf_storage_directory: \"/usr/local/lib/redmine/redmine/files/dmsf\"\ndmsf_default_notifications: \'1\'\ndmsf_display_notified_recipients: \'1\'\ndmsf_webdav: \'1\'\ndmsf_webdav_strategy: WEBDAV_READ_ONLY\ndmsf_index_database: \"/usr/local/lib/redmine/redmine/files/dmsf_index\"\ndmsf_stemming_lang: french\ndmsf_stemming_strategy: STEM_NONE\n', NOW()) ON DUPLICATE KEY UPDATE `value` = '--- !ruby/hash:ActionController::Parameters\ndmsf_max_file_upload: \'10\'\ndmsf_max_file_download: \'10\'\ndmsf_max_email_filesize: \'35\'\ndmsf_max_ajax_upload_filesize: \'10\'\ndmsf_storage_directory: \"/usr/local/lib/redmine/redmine/files/dmsf\"\ndmsf_default_notifications: \'1\'\ndmsf_display_notified_recipients: \'1\'\ndmsf_webdav: \'1\'\ndmsf_webdav_strategy: WEBDAV_READ_ONLY\ndmsf_index_database: \"/usr/local/lib/redmine/redmine/files/dmsf_index\"\ndmsf_stemming_lang: french\ndmsf_stemming_strategy: STEM_NONE\n', `updated_on` = NOW();

/* plugin CKEditor */
INSERT INTO `settings` (`name`, `value`, `updated_on`) VALUES ('plugin_redmine_ckeditor', '--- !ruby/hash:ActionController::Parameters\nskin: moono\nui_color: \"#f4f4f4\"\nwidth: \'\'\nheight: \'400\'\nenter_mode: \'1\'\nshow_blocks: \'1\'\ntoolbar_can_collapse: \'0\'\ntoolbar_location: top\ntoolbar: Source,ShowBlocks,RemoveFormat,--,Undo,Redo,-,Cut,Copy,Paste,PasteText,PasteFromWord,-,Scayt,--,Bold,Italic,Underline,Strike,-,Subscript,Superscript,-,NumberedList,BulletedList,-,Outdent,Indent,Blockquote,-,JustifyLeft,JustifyCenter,JustifyRight,JustifyBlock,-,/,Styles,Format,Font,FontSize,-,TextColor,BGColor,-,--,HorizontalRule,Table,Link,Unlink,Anchor,Smiley,richImage,Iframe,MediaEmbed,-,--,Maximize,-\n', NOW()) ON DUPLICATE KEY UPDATE `value` = '--- !ruby/hash:ActionController::Parameters\nskin: moono\nui_color: \"#f4f4f4\"\nwidth: \'\'\nheight: \'400\'\nenter_mode: \'1\'\nshow_blocks: \'1\'\ntoolbar_can_collapse: \'0\'\ntoolbar_location: top\ntoolbar: Source,ShowBlocks,RemoveFormat,--,Undo,Redo,-,Cut,Copy,Paste,PasteText,PasteFromWord,-,Scayt,--,Bold,Italic,Underline,Strike,-,Subscript,Superscript,-,NumberedList,BulletedList,-,Outdent,Indent,Blockquote,-,JustifyLeft,JustifyCenter,JustifyRight,JustifyBlock,-,/,Styles,Format,Font,FontSize,-,TextColor,BGColor,-,--,HorizontalRule,Table,Link,Unlink,Anchor,Smiley,richImage,Iframe,MediaEmbed,-,--,Maximize,-\n', `updated_on` = NOW();

/* Unread issues */
/*INSERT INTO `settings` (`name`, `value`, `updated_on`) VALUES ('plugin_unread_issues','--- !ruby/hash:ActionController::Parameters\nassigned_issues: \'1\'\n', NOW()) ON DUPLICATE KEY UPDATE `value` = '--- !ruby/hash:ActionController::Parameters\nassigned_issues: \'1\'\n', `updated_on` = NOW();*/

